---
# Install Nginx
- name: Install eper-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
#######################
- name: Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
#######################
- name: Enable Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
