---
# Install Clickhouse 
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
# Install Nginx on lighthouse and vector hosts
- name: Install Nginx
  hosts: lighthouse:vector
  roles:
    - nginx
# Install Lighthouse
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse

# Install Vector
- name: Install Vector
  hosts: vector
  roles:
    - vector
