---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
 - name: instance
   image: pycontribs/centos:7
   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
  - create
  - verify
  - destroy
