---
vector_url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
nginx_user_name: root
# Указать для vector_conf_endpoint ['hostname'] сервера с БД clickhouse
vector_conf_endpoint: http://192.168.1.101:8123
vector_config:
  sources:
    our_log:
      ignore_older_secs: 600
      include:
        - /var/log/nginx/access.log
      read_from: beginning
      type: file
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - our_log
      database: logs
      endpoint: "{{ vector_conf_endpoint }}"
      table: access_logs
      compression: gzip
      healthcheck: false
      skip_unknown_fields: true
